# Gopkg.toml example
[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/yunabe/lgo"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"
